<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img-succes</name>
   <tag></tag>
   <elementGuidId>2ff4dcf2-03dc-4647-a120-93f8b9edec8f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./../assets/images/successImage.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;body&quot;]/app-root[1]/div[@class=&quot;p2p&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;container split1&quot;]/div[@class=&quot;main-wrapper&quot;]/app-p2p[1]/div[@class=&quot;mainP2pContent success-content&quot;]/div[@class=&quot;success-img-holder&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
