<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NEXT_otp</name>
   <tag></tag>
   <elementGuidId>df79d451-852f-44fa-b80f-a58c95bcb9f9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Продолжить
        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;body&quot;]/app-root[1]/div[@class=&quot;p2p&quot;]/app-ui-sub-navigation[1]/registration[@class=&quot;registrationModule&quot;]/div[@class=&quot;reg-register-form&quot;]/div[@class=&quot;reg-register-form__actions-holder&quot;]/div[@class=&quot;reg-register-form__actions-block&quot;]/app-otp-form[@class=&quot;form-holder&quot;]/div[@class=&quot;reg-form-wrapper reg-otp-form&quot;]/div[@class=&quot;reg-actions-block__sms-confirm&quot;]/div[@class=&quot;controls&quot;]/button[@class=&quot;reg-button&quot;]</value>
   </webElementProperties>
</WebElementEntity>
