<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-3-valid-date</name>
   <tag></tag>
   <elementGuidId>a10fe854-4095-4945-95d0-a61507a01929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@class = 'md-input-element ng-untouched ng-pristine ng-valid']) = count(//*[@class = 'md-input-element ng-untouched ng-pristine ng-valid'])][count(. | //*[@ng-reflect-required = 'false']) = count(//*[@ng-reflect-required = 'false'])][count(. | //*[@ng-reflect-is-disabled = 'false']) = count(//*[@ng-reflect-is-disabled = 'false'])][count(. | //*[@id = 'md-input-3-input']) = count(//*[@id = 'md-input-3-input'])][count(. | //*[@maxlength = '5']) = count(//*[@maxlength = '5'])][count(. | //*[@spellcheck = 'false']) = count(//*[@spellcheck = 'false'])][count(. | //*[@type = 'text']) = count(//*[@type = 'text'])][count(. | id(&quot;md-input-3-input&quot;)) = count(id(&quot;md-input-3-input&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-input-element ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>md-input-3-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;md-input-3-input&quot;)</value>
   </webElementProperties>
</WebElementEntity>
